use_frameworks!

target 'SSLibrarySDK_Example' do
  pod 'SSLibrarySDK', :path => '../'

  target 'SSLibrarySDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
